name: Release
on:
  release:
    types:
      - created
jobs:
  release_212:
    name: Release 2.12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      name: Setup Java
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'sbt'
        gpg-private-key: ${{ secrets.PGP_SECRET }}
        gpg-passphrase: ${{ secrets.PGP_PASSPHRASE }}
    - name: Release for Scala 2.12
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      run: CI_RELEASE=publishSigned sbt ++2.12.17 releaseIt

  release_213:
    name: Release 2.13
    needs: release_212
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      name: Setup Java
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'sbt'
        gpg-private-key: ${{ secrets.PGP_SECRET }}
        gpg-passphrase: ${{ secrets.PGP_PASSPHRASE }}
    - name: Release for Scala 2.12
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      run: CI_RELEASE=publishSigned sbt ++2.13.10 releaseIt
